a = 6
print("a = ", a)
a += 1
print("a + 1 =", a)
print("\na = ", a)
a -= 1
print("a - 1 =", a)
print("\na = ", a)
a *= 2
print("a * 2 =", a)
print("\na = ", a)
a /= 2
print("a / 2 =", a)
print("\na = ", a)
a **= 2
print("a ** 2 =", a)
print("\na = ", a)
a %= 2
print("a % 2 =", a)
